#!/usr/bin/env bash
#
# recon.sh — authorized bug bounty recon + vuln scan pipeline
#
# ============================================================================
# LEGAL / SCOPE WARNING
# Only run this against targets you are explicitly authorized to test
# (e.g. domains listed in a bug bounty program's scope, with permission).
# Unauthorized scanning of systems you don't own or have written permission
# to test is illegal in most jurisdictions (e.g. under the US CFAA, UK
# Computer Misuse Act, etc.) regardless of intent.
# ============================================================================
#
# Pipeline stages:
#   1. subfinder  -> passive subdomain enumeration
#   2. httpx      -> probe which hosts are alive (HTTP/S), grab metadata
#   3. naabu      -> fast port scan on live hosts
#   4. nuclei     -> template-based scanning for known CVEs & misconfigs
#
# Requires (install once, see install.sh):
#   subfinder, httpx, naabu, nuclei  (all from ProjectDiscovery, Go tools)
#
# Usage:
#   ./recon.sh -d target.com [-o output_dir] [-r nuclei_rate] [-s severity]
#
# Output:
#   <output_dir>/subdomains.txt
#   <output_dir>/live_hosts.txt
#   <output_dir>/ports.txt
#   <output_dir>/nuclei_results.jsonl
#   <output_dir>/report.md   (generated by report.py)
#
set -euo pipefail

# ---------- defaults ----------
TARGET=""
OUTDIR=""
NUCLEI_RATE=150
SEVERITY="low,medium,high,critical"
THREADS=50
SKIP_CONFIRM=false

usage() {
  echo "Usage: $0 -d <domain> [-o <output_dir>] [-r <nuclei_rate_limit>] [-s <severities>] [-y]"
  echo "  -d   Root domain to recon (must be in-scope for your authorization)"
  echo "  -o   Output directory (default: results/<domain>_<timestamp>)"
  echo "  -r   Nuclei requests/sec rate limit (default: 150; lower = stealthier/safer)"
  echo "  -s   Comma-separated nuclei severities (default: low,medium,high,critical)"
  echo "  -y   Skip the interactive re-type-to-confirm prompt"
  echo "       (use only once you've already verified scope for this target)"
  exit 1
}

while getopts "d:o:r:s:yh" opt; do
  case $opt in
    d) TARGET="$OPTARG" ;;
    o) OUTDIR="$OPTARG" ;;
    r) NUCLEI_RATE="$OPTARG" ;;
    s) SEVERITY="$OPTARG" ;;
    y) SKIP_CONFIRM=true ;;
    h) usage ;;
    *) usage ;;
  esac
done

[[ -z "$TARGET" ]] && usage

TS=$(date +%Y%m%d_%H%M%S)
OUTDIR="${OUTDIR:-results/${TARGET}_${TS}}"
mkdir -p "$OUTDIR"

echo "=============================================="
echo " Target        : $TARGET"
echo " Output dir    : $OUTDIR"
echo " Nuclei rate   : $NUCLEI_RATE req/s"
echo " Severities    : $SEVERITY"
echo "=============================================="
echo
if [[ "$SKIP_CONFIRM" == true ]]; then
  echo "(-y passed: skipping re-type confirmation — make sure you already verified scope)"
else
  echo "!! Confirm this target is in your authorized scope before continuing. !!"
  read -r -p "Type the target domain again to confirm and proceed: " CONFIRM
  if [[ "$CONFIRM" != "$TARGET" ]]; then
    echo "Confirmation did not match target. Aborting."
    exit 1
  fi
fi

# ---------- resolve tools by explicit path ----------
# Kali (and other distros) sometimes have unrelated tools with the same name
# on PATH (e.g. the Python "httpx" HTTP client library CLI collides with
# ProjectDiscovery's Go "httpx" recon tool). Prefer the Go-installed binary
# by explicit path so we never accidentally run the wrong "httpx".
GOBIN="$(go env GOPATH 2>/dev/null)/bin"

resolve_tool() {
  local name="$1"
  if [[ -x "$GOBIN/$name" ]]; then
    echo "$GOBIN/$name"
  else
    command -v "$name" 2>/dev/null || true
  fi
}

SUBFINDER_BIN=$(resolve_tool subfinder)
HTTPX_BIN=$(resolve_tool httpx)
NAABU_BIN=$(resolve_tool naabu)
NUCLEI_BIN=$(resolve_tool nuclei)

check_tool() {
  local name="$1"
  local path="$2"
  if [[ -z "$path" ]]; then
    echo "[!] Missing required tool: $name"
    echo "    Run ./install_kali.sh first, or see https://github.com/projectdiscovery/$name"
    exit 1
  fi
}
check_tool subfinder "$SUBFINDER_BIN"
check_tool httpx "$HTTPX_BIN"
check_tool naabu "$NAABU_BIN"
check_tool nuclei "$NUCLEI_BIN"

echo "Using tools:"
echo "  subfinder: $SUBFINDER_BIN"
echo "  httpx:     $HTTPX_BIN"
echo "  naabu:     $NAABU_BIN"
echo "  nuclei:    $NUCLEI_BIN"

# ---------- 1. Subdomain enumeration ----------
echo "[1/4] Enumerating subdomains with subfinder..."
"$SUBFINDER_BIN" -d "$TARGET" -silent -all -o "$OUTDIR/subdomains.txt"
SUB_COUNT=$(wc -l < "$OUTDIR/subdomains.txt" || echo 0)
echo "      -> $SUB_COUNT subdomains found"

# ---------- 2. Live host probing ----------
echo "[2/4] Probing for live hosts with httpx..."
"$HTTPX_BIN" -l "$OUTDIR/subdomains.txt" -silent -follow-redirects \
  -status-code -title -tech-detect -threads "$THREADS" \
  -o "$OUTDIR/live_hosts.txt"
LIVE_COUNT=$(wc -l < "$OUTDIR/live_hosts.txt" || echo 0)
echo "      -> $LIVE_COUNT live hosts"

# extract just the bare hostnames/URLs for downstream tools
awk '{print $1}' "$OUTDIR/live_hosts.txt" > "$OUTDIR/live_hosts_clean.txt"

# naabu needs bare hostnames/IPs, not full URLs with scheme+path — strip those
sed -E 's#^https?://##; s#/.*$##; s#:[0-9]+$##' "$OUTDIR/live_hosts_clean.txt" \
  | sort -u > "$OUTDIR/naabu_targets.txt"

# ---------- 3. Port scanning ----------
echo "[3/4] Scanning ports with naabu..."
"$NAABU_BIN" -list "$OUTDIR/naabu_targets.txt" -silent \
  -top-ports 1000 -o "$OUTDIR/ports.txt" || true
PORT_COUNT=0
[[ -f "$OUTDIR/ports.txt" ]] && PORT_COUNT=$(wc -l < "$OUTDIR/ports.txt")
echo "      -> $PORT_COUNT open host:port pairs"

# ---------- 4. Vulnerability / misconfig scanning ----------
echo "[4/4] Running nuclei templates (CVEs + misconfigs)..."
"$NUCLEI_BIN" -l "$OUTDIR/live_hosts_clean.txt" \
  -severity "$SEVERITY" \
  -rate-limit "$NUCLEI_RATE" \
  -silent \
  -o "$OUTDIR/nuclei_results.txt" \
  -je "$OUTDIR/nuclei_results.json" || true
FINDINGS=0
if [[ -f "$OUTDIR/nuclei_results.json" ]]; then
  FINDINGS=$(python3 -c "import json,sys
try:
    print(len(json.load(open(sys.argv[1]))))
except Exception:
    print(0)" "$OUTDIR/nuclei_results.json")
fi
echo "      -> $FINDINGS findings"

# ---------- Report ----------
echo
echo "Generating report..."
python3 "$(dirname "$0")/report.py" "$OUTDIR"

echo
echo "Done. Results in: $OUTDIR"
echo "Report: $OUTDIR/report.md"

# ---------- Follow-up: optional next stages ----------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

ask_yes_no() {
  local prompt="$1"
  local answer
  if [[ "$SKIP_CONFIRM" == true ]]; then
    # -y was passed for the whole run: default follow-up stages to "no"
    # so unattended runs never hang waiting for input.
    echo "$prompt (skipped — running with -y)"
    return 1
  fi
  while true; do
    read -r -p "$prompt [y/n]: " answer
    case "$answer" in
      [Yy]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo]) return 1 ;;
      *) echo "Please type yes or no." ;;
    esac
  done
}

echo
echo "Optional follow-up scans available. For each one, type y to run it"
echo "now, or n to skip (you can always run it manually later)."

# name | script | description
OPTIONAL_STAGES=(
  "js_analysis.sh|Analyze JS files for leaked keys/tokens"
  "takeover_check.sh|Check for subdomain takeovers"
  "bypass_403.sh|Check 403/401 hosts for access-control bypass"
  "screenshot.sh|Screenshot every live host"
  "historical_urls.sh|Pull historical/archived URLs (Wayback Machine)"
)

for stage in "${OPTIONAL_STAGES[@]}"; do
  script="${stage%%|*}"
  desc="${stage#*|}"
  echo
  if ask_yes_no "Run '$script' now? ($desc)"; then
    if [[ -x "$SCRIPT_DIR/$script" ]]; then
      "$SCRIPT_DIR/$script" "$OUTDIR"
    else
      echo "[!] $script not found or not executable in $SCRIPT_DIR — skipping"
    fi
  else
    echo "Skipped. Run it later with: ./$script $OUTDIR"
  fi
done

echo
echo "All optional stages done (or skipped). Final results in: $OUTDIR"